swagger: '2.0'
info:
  description: Интеграция СЭД-СМЭВ3-ПОС
  version: '1.0'
  title: MS.POS_ADAPTER
host: localhost:8080
basePath: /
tags:
  - name: MS.POS_Adapter
    description: Departament Controller
paths:
  /departament:
    put:
      tags:
        - MS.POS_Adapter
      summary: Отправка данных о департаментах
      operationId: addDepsUsingPUT
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - in: body
          name: request body
          description: Тело запроса
          required: false
          schema:
            $ref: '#/definitions/DepRequest'
      responses:
        '200':
          description: Успех
          schema:
            $ref: '#/definitions/Response'
        '400':
          description: Неверный формат запроса
          schema:
            $ref: '#/definitions/ValidErrorResponse'
        '500':
          description: Внутренняя ошибка сервиса
          schema:
            $ref: '#/definitions/ErrorResponse'
      deprecated: false
  /file:
    get:
      tags:
        - MS.POS_Adapter
      summary: Получение файла
      operationId: getFileUsingGET
      produces:
        - '*/*'
      parameters:
        - name: fileUUID
          in: query
          description: Идентификатор файла
          required: true
          type: string
          allowEmptyValue: false
          x-example: 2beeef67-8f2d-4223-9faf-34663033265c
      responses:
        '200':
          description: Успех
          schema:
            $ref: '#/definitions/FileResponse'
        '400':
          description: Неверный формат запроса
          schema:
            $ref: '#/definitions/ValidErrorResponse'
        '404':
          description: Файл не найден
          schema:
            $ref: '#/definitions/ErrorResponse'
        '500':
          description: Внутренняя ошибка сервиса
          schema:
            $ref: '#/definitions/ErrorResponse'
      deprecated: false
  /list:
    get:
      tags:
        - MS.POS_Adapter
      summary: Получение обращений
      operationId: getAppealListUsingGET
      produces:
        - '*/*'
      parameters:
        - name: appealDate
          in: query
          description: 'После указанной даты обращения. Формат: yyyy-MM-dd'
          required: false
          type: string
          allowEmptyValue: false
          x-example: '2021-05-07'
        - name: appealStatus
          in: query
          description: Статус обращения
          required: false
          type: string
          allowEmptyValue: false
          x-example: GETTED_FROM_POS
          enum:
            - GETTED_FROM_POS
            - GETTED_FROM_POS_NO_FILES
            - ACCEPTED
            - SENDED_TO_POS
        - name: clientId
          in: query
          description: Идентификатор клиента
          required: false
          type: string
          allowEmptyValue: false
          x-example: a0b0d327-977a-4c93-b4ea-76a07365e153
        - name: limit
          in: query
          description: Макс. кол-во возвращаемых данных (макс. 100)
          required: false
          type: integer
          default: 100
          format: int32
          allowEmptyValue: false
          x-example: 100
      responses:
        '200':
          description: Успех
          schema:
            $ref: '#/definitions/ListResponse'
        '400':
          description: Неверный формат запроса
          schema:
            $ref: '#/definitions/ValidErrorResponse'
        '500':
          description: Внутренняя ошибка сервиса
          schema:
            $ref: '#/definitions/ErrorResponse'
      deprecated: false
  /markAccepted:
    put:
      tags:
        - MS.POS_Adapter
      summary: Отправка отметки о взятии обращений в работу
      operationId: markAppealUsingPUT
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - name: appealId
          in: query
          description: Идентификатор обращения
          required: true
          type: integer
          format: int64
          allowEmptyValue: false
          x-example: 4654
      responses:
        '200':
          description: Успех
          schema:
            $ref: '#/definitions/Response'
        '400':
          description: Неверный формат запроса
          schema:
            $ref: '#/definitions/ValidErrorResponse'
        '404':
          description: Обращение не найдено
          schema:
            $ref: '#/definitions/ValidErrorResponse'
        '500':
          description: Внутренняя ошибка сервиса
          schema:
            $ref: '#/definitions/ErrorResponse'
      deprecated: false
  /statusAndFiles:
    put:
      tags:
        - MS.POS_Adapter
      summary: Отправка изменения статуса обращения и передача файлов
      operationId: updStatusAndAddFilesUsingPUT
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - in: body
          name: request body
          description: Тело запроса
          required: false
          schema:
            $ref: '#/definitions/StatusAndFilesRequest'
      responses:
        '200':
          description: Успех
          schema:
            $ref: '#/definitions/Response'
        '400':
          description: Неверный формат запроса
          schema:
            $ref: '#/definitions/ValidErrorResponse'
        '500':
          description: Внутренняя ошибка сервиса
          schema:
            $ref: '#/definitions/ErrorResponse'
      deprecated: false
definitions:
  AddressType:
    type: object
    properties:
      Id:
        type: integer
        format: int64
        example: 1
        xml:
          name: Id
          attribute: false
          wrapped: false
        description: ИД записи
      PostalCode:
        type: string
        example: '018233'
        xml:
          name: PostalCode
          attribute: false
          wrapped: false
        description: Почтовый индекс
      Country:
        type: string
        example: string
        xml:
          name: Country
          attribute: false
          wrapped: false
        description: Наименование страны
      RegionFiasId:
        type: string
        example: string
        xml:
          name: RegionFiasId
          attribute: false
          wrapped: false
        description: ФИАС идентификатор региона
      RegionKladrId:
        type: string
        example: string
        xml:
          name: RegionKladrId
          attribute: false
          wrapped: false
        description: ФИАС идентификатор региона
      RegionWithType:
        type: string
        example: string
        xml:
          name: RegionWithType
          attribute: false
          wrapped: false
        description: Регион с описанием типа
      RegionType:
        type: string
        example: string
        xml:
          name: RegionType
          attribute: false
          wrapped: false
        description: Тип региона
      RegionTypeFull:
        type: string
        example: string
        xml:
          name: RegionTypeFull
          attribute: false
          wrapped: false
        description: Регион с полным описанием типа
      AreaFiasId:
        type: string
        example: string
        xml:
          name: AreaFiasId
          attribute: false
          wrapped: false
        description: ФИАС идентификатор области
      AreaKladrId:
        type: string
        example: string
        xml:
          name: AreaKladrId
          attribute: false
          wrapped: false
        description: КЛАДР идентификатор области
      AreaWithType:
        type: string
        example: string
        xml:
          name: AreaWithType
          attribute: false
          wrapped: false
        description: Регион с описанием типа
      AreaType:
        type: string
        example: string
        xml:
          name: AreaType
          attribute: false
          wrapped: false
        description: Тип области
      AreaTypeFull:
        type: string
        example: string
        xml:
          name: AreaTypeFull
          attribute: false
          wrapped: false
        description: Область с полным описанием типа
      Area:
        type: string
        example: string
        xml:
          name: Area
          attribute: false
          wrapped: false
        description: Наименование области/региона
      CityFiasId:
        type: string
        example: Москва
        xml:
          name: CityFiasId
          attribute: false
          wrapped: false
        description: ФИАС идентификатор области
      CityKladrId:
        type: string
        example: Москва
        xml:
          name: CityKladrId
          attribute: false
          wrapped: false
        description: Город с описанием типа
      CityWithType:
        type: string
        example: Москва
        xml:
          name: CityWithType
          attribute: false
          wrapped: false
        description: Город с описанием типа
      CityType:
        type: string
        example: Москва
        xml:
          name: CityType
          attribute: false
          wrapped: false
        description: Тип города
      CityTypeFull:
        type: string
        example: Москва
        xml:
          name: CityTypeFull
          attribute: false
          wrapped: false
        description: Город с полным описанием типа
      City:
        type: string
        example: Москва
        xml:
          name: City
          attribute: false
          wrapped: false
        description: Наименование города
      CityArea:
        type: string
        example: Москва
        xml:
          name: CityArea
          attribute: false
          wrapped: false
        description: Область города
      CityDistrictFiasId:
        type: string
        example: Москва
        xml:
          name: CityDistrictFiasId
          attribute: false
          wrapped: false
        description: ФИАС идентификатор района города
      CityDistrictKladrId:
        type: string
        example: Москва
        xml:
          name: CityDistrictKladrId
          attribute: false
          wrapped: false
        description: КЛАДР идентификатор района города
      CityDistrictWithType:
        type: string
        example: Москва
        xml:
          name: CityDistrictWithType
          attribute: false
          wrapped: false
        description: Район города с описанием типа
      CityDistrictType:
        type: string
        example: Москва
        xml:
          name: CityDistrictType
          attribute: false
          wrapped: false
        description: Тип района города
      CityDistrictTypeFull:
        type: string
        example: Москва
        xml:
          name: CityDistrictTypeFull
          attribute: false
          wrapped: false
        description: Район города с полным описанием типа
      CityDistrict:
        type: string
        example: Москва
        xml:
          name: CityDistrict
          attribute: false
          wrapped: false
        description: Наименование района города
      SettlementFiasId:
        type: string
        example: string
        xml:
          name: SettlementFiasId
          attribute: false
          wrapped: false
        description: ФИАС идентификатор поселения
      SettlementKladrId:
        type: string
        example: string
        xml:
          name: SettlementKladrId
          attribute: false
          wrapped: false
        description: КЛАДР идентификатор поселения
      SettlementWithType:
        type: string
        example: string
        xml:
          name: SettlementWithType
          attribute: false
          wrapped: false
        description: Поселение с описанием типа
      SettlementType:
        type: string
        example: string
        xml:
          name: SettlementType
          attribute: false
          wrapped: false
        description: Тип поселения
      SettlementTypeFull:
        type: string
        example: string
        xml:
          name: SettlementTypeFull
          attribute: false
          wrapped: false
        description: Поселение с полным описанием типа
      Settlement:
        type: string
        example: string
        xml:
          name: Settlement
          attribute: false
          wrapped: false
        description: Наименование поселения
      StreetFiasId:
        type: string
        example: Землянной вал
        xml:
          name: StreetFiasId
          attribute: false
          wrapped: false
        description: ФИАС идентификатор улицы
      StreetKladrId:
        type: string
        example: Землянной вал
        xml:
          name: StreetKladrId
          attribute: false
          wrapped: false
        description: КЛАДР идентификатор улицы
      StreetWithType:
        type: string
        example: Землянной вал
        xml:
          name: StreetWithType
          attribute: false
          wrapped: false
        description: Улица с описанием типа
      StreetType:
        type: string
        example: Землянной вал
        xml:
          name: StreetType
          attribute: false
          wrapped: false
        description: Тип улицы
      StreetTypeFull:
        type: string
        example: Землянной вал
        xml:
          name: StreetTypeFull
          attribute: false
          wrapped: false
        description: Улица с полным описанием типа
      Street:
        type: string
        example: Землянной вал
        xml:
          name: Street
          attribute: false
          wrapped: false
        description: Наименование улицы
      HouseFiasId:
        type: string
        example: 32
        xml:
          name: HouseFiasId
          attribute: false
          wrapped: false
        description: ФИАС идентификатор дома
      HouseKladrId:
        type: string
        example: 32
        xml:
          name: HouseKladrId
          attribute: false
          wrapped: false
        description: КЛАДР идентификатор дома
      HouseType:
        type: string
        example: 32
        xml:
          name: HouseType
          attribute: false
          wrapped: false
        description: Тип дома
      HouseTypeFull:
        type: string
        example: 32
        xml:
          name: HouseTypeFull
          attribute: false
          wrapped: false
        description: Дом с полным описанием типа
      House:
        type: string
        example: 32
        xml:
          name: House
          attribute: false
          wrapped: false
        description: Наименование дома
      BlockType:
        type: string
        example: string
        xml:
          name: BlockType
          attribute: false
          wrapped: false
        description: Тип корпуса
      BlockTypeFull:
        type: string
        example: string
        xml:
          name: BlockTypeFull
          attribute: false
          wrapped: false
        description: Корпус с полным описанием типа
      Block:
        type: string
        example: string
        xml:
          name: Block
          attribute: false
          wrapped: false
        description: Наименование корпуса
      FlatType:
        type: string
        example: 23
        xml:
          name: FlatType
          attribute: false
          wrapped: false
        description: Тип квартиры
      FlatTypeFull:
        type: string
        example: 23
        xml:
          name: FlatTypeFull
          attribute: false
          wrapped: false
        description: Квартира с полным описанием типа
      Flat:
        type: string
        example: 23
        xml:
          name: Flat
          attribute: false
          wrapped: false
        description: Наименование квартиры
      FlatArea:
        type: number
        format: double
        example: 1
        xml:
          name: FlatArea
          attribute: false
          wrapped: false
        description: Площадь квартиры
      SquareMeterPrice:
        type: number
        format: double
        example: 1
        xml:
          name: SquareMeterPrice
          attribute: false
          wrapped: false
        description: Цена квадратного метра квартир
      FlatPrice:
        type: number
        format: double
        example: 1
        xml:
          name: FlatPrice
          attribute: false
          wrapped: false
        description: Стоимость квартиры
      PostalBox:
        type: string
        example: string
        xml:
          name: PostalBox
          attribute: false
          wrapped: false
        description: Почтовый ящик
      FiasId:
        type: string
        example: string
        xml:
          name: FiasId
          attribute: false
          wrapped: false
        description: ФИАС идентификатор адреса
      FiasCode:
        type: string
        example: 5ee84ac0-eb9a-4b42-b814-2f5f7c27c255
        xml:
          name: FiasCode
          attribute: false
          wrapped: false
        description: ФИАС код адреса
      FiasLevel:
        type: string
        example: string
        xml:
          name: FiasLevel
          attribute: false
          wrapped: false
        description: ФИАС уровень адреса
      FiasActualityState:
        type: string
        example: string
        xml:
          name: FiasActualityState
          attribute: false
          wrapped: false
        description: Актуальное состояние ФИАС
      KladrId:
        type: string
        example: string
        xml:
          name: KladrId
          attribute: false
          wrapped: false
        description: КЛАДР идентификатор адреса
      GeonameId:
        type: string
        example: string
        xml:
          name: GeonameId
          attribute: false
          wrapped: false
        description: Идентификатор геолокации
      CapitalMarker:
        type: string
        example: string
        xml:
          name: CapitalMarker
          attribute: false
          wrapped: false
        description: Рынок капитала адреса
      Okato:
        type: string
        example: 36234836003
        xml:
          name: Okato
          attribute: false
          wrapped: false
        description: ОКАТО
      Oktmo:
        type: string
        example: string
        xml:
          name: Oktmo
          attribute: false
          wrapped: false
        description: ОКТМО
      TaxOffice:
        type: string
        example: string
        xml:
          name: TaxOffice
          attribute: false
          wrapped: false
        description: Налоговая служба
      TaxOfficeLegal:
        type: string
        example: string
        xml:
          name: TaxOfficeLegal
          attribute: false
          wrapped: false
        description: Налоговая инспекция
      Timezone:
        type: string
        example: string
        xml:
          name: Timezone
          attribute: false
          wrapped: false
        description: Часовой пояс
      GeoLat:
        type: number
        format: double
        example: 1
        xml:
          name: GeoLat
          attribute: false
          wrapped: false
        description: Географическая широта
      GeoLon:
        type: number
        format: double
        example: 1
        xml:
          name: GeoLon
          attribute: false
          wrapped: false
        description: Географическая долгота
      BeltwayHit:
        type: string
        example: string
        xml:
          name: BeltwayHit
          attribute: false
          wrapped: false
        description: Внутри кольцевой?
      BeltwayDistance:
        type: number
        format: double
        example: 1
        xml:
          name: BeltwayDistance
          attribute: false
          wrapped: false
        description: Расстояние от кольцевой в километрах
      QcGeo:
        type: string
        example: string
        xml:
          name: QcGeo
          attribute: false
          wrapped: false
        description: Код точности координат
      QcComplete:
        type: string
        example: string
        xml:
          name: QcComplete
          attribute: false
          wrapped: false
        description: Подходит для рассылки?
      QcHouse:
        type: string
        example: 32
        xml:
          name: QcHouse
          attribute: false
          wrapped: false
        description: Признак наличия дома в ФИАС
      HistoryValues:
        type: array
        xml:
          name: HistoryValues
          namespace: http://pos.gosuslugi.ru/edms/appeal/common/1.1.0
          attribute: false
          wrapped: true
        description: История значений
        items:
          type: string
      UnparsedParts:
        type: string
        example: string
        xml:
          name: UnparsedParts
          attribute: false
          wrapped: false
        description: Неразобранные части
      Source:
        type: string
        example: string
        xml:
          name: Source
          attribute: false
          wrapped: false
        description: Источник
      Qc:
        type: string
        example: string
        xml:
          name: Qc
          attribute: false
          wrapped: false
        description: Код проверки - требуется ли вручную проверить распознанное значение
      RegionId:
        type: integer
        format: int64
        example: 1
        xml:
          name: RegionId
          attribute: false
          wrapped: false
        description: Идентификатор региона
    title: AddressType
    xml:
      name: AddressType
      namespace: http://pos.gosuslugi.ru/edms/appeal/common/1.1.0
      attribute: false
      wrapped: false
    description: Адрес
  ApplicantType:
    type: object
    properties:
      Surname:
        type: string
        example: string
        xml:
          name: Surname
          attribute: false
          wrapped: false
        description: Фамилия заявителя
      Name:
        type: string
        example: string
        xml:
          name: Name
          attribute: false
          wrapped: false
        description: Имя заявителя
      Patronymic:
        type: string
        example: string
        xml:
          name: Patronymic
          attribute: false
          wrapped: false
        description: Отчество заявителя
      Email:
        type: string
        example: example@example.org
        xml:
          name: Email
          attribute: false
          wrapped: false
        description: Электронная почта
      Phone:
        type: string
        example: (123) 456-7890
        xml:
          name: Phone
          attribute: false
          wrapped: false
        description: Телефон
      PostAddress:
        type: string
        example: string
        xml:
          name: PostAddress
          attribute: false
          wrapped: false
        description: Адрес
      SendWithRussiaPost:
        type: boolean
        example: false
        xml:
          name: SendWithRussiaPost
          attribute: false
          wrapped: false
        description: Признак необходимости отправки ответа по почте
    title: ApplicantType
    xml:
      name: ApplicantType
      attribute: false
      wrapped: false
    description: Информация о персоне
  CustomFieldValueType:
    type: object
    required:
      - CustomFieldId
      - FieldType
      - Id
      - Name
      - Value
    properties:
      Id:
        type: integer
        format: int64
        example: 1
        xml:
          name: Id
          attribute: false
          wrapped: false
        description: ИД значения настраиваемого поля
      Name:
        type: string
        example: string
        xml:
          name: Name
          attribute: false
          wrapped: false
        description: Наименование настраиваемого поля
      Value:
        type: string
        example: string
        xml:
          name: Value
          attribute: false
          wrapped: false
        description: Значение настраиваемого поля
      CustomFieldId:
        type: integer
        format: int64
        example: 1
        xml:
          name: CustomFieldId
          attribute: false
          wrapped: false
        description: ИД настраиваемого поля
      FieldType:
        type: string
        example: string
        xml:
          name: FieldType
          attribute: false
          wrapped: false
        description: Тип настраиваемого поля
      DictionaryId:
        type: integer
        format: int64
        example: 1
        xml:
          name: DictionaryId
          attribute: false
          wrapped: false
        description: ИД справочника
      DictionaryValues:
        type: array
        xml:
          name: DictionaryValues
          namespace: http://pos.gosuslugi.ru/edms/appeal/common/1.1.0
          attribute: false
          wrapped: true
        description: ИД справочника
        items:
          $ref: '#/definitions/DictionaryValueType'
      Description:
        type: string
        example: string
        xml:
          name: Description
          attribute: false
          wrapped: false
        description: Описание настраиваемого значения
    title: CustomFieldValueType
    xml:
      name: CustomFieldValueType
      attribute: false
      wrapped: false
    description: Значение настраиваемого поля
  DepRequest:
    type: object
    required:
      - Departaments
    properties:
      Departaments:
        type: array
        example:
          - a0b0d327-977a-4c93-b4ea-76a07365e153
        description: Данные о департаментах
        items:
          type: string
    title: DepRequest
    description: DepRequest
  DictionaryValueType:
    type: object
    required:
      - Id
      - Name
    properties:
      Id:
        type: integer
        format: int64
        example: 1
        xml:
          name: Id
          attribute: false
          wrapped: false
        description: ИД справочного значения
      Name:
        type: string
        example: string
        xml:
          name: Name
          attribute: false
          wrapped: false
        description: Наименование справочного значения
    title: DictionaryValueType
    xml:
      name: DictionaryValueType
      namespace: http://pos.gosuslugi.ru/edms/appeal/common/1.1.0
      attribute: false
      wrapped: false
    description: Значение справочника
  EdmsAppealType:
    type: object
    required:
      - AnswerAt
      - Applicant
      - CreatedAt
      - Description
      - FastTrack
      - Id
      - OpaId
      - OpaName
      - RegionId
      - RegionName
      - Shared
      - SubjectId
      - SubjectName
      - SubsubjectId
      - SubsubjectName
    properties:
      Id:
        type: integer
        format: int64
        example: 1
        xml:
          name: Id
          attribute: false
          wrapped: false
        description: ИД сообщения
      Description:
        type: string
        example: string
        xml:
          name: Description
          attribute: false
          wrapped: false
        description: Текст сообщения
      RegNumber:
        type: string
        example: 42
        xml:
          name: RegNumber
          attribute: false
          wrapped: false
        description: Регистрационный номер
      RegNumberSetAt:
        type: string
        xml:
          name: RegNumberSetAt
          attribute: false
          wrapped: false
        description: Дата присвоения регистрационного номера
      SubjectId:
        type: integer
        format: int64
        example: 1
        xml:
          name: SubjectId
          attribute: false
          wrapped: false
        description: ИД категории
      SubjectName:
        type: string
        example: string
        xml:
          name: SubjectName
          attribute: false
          wrapped: false
        description: Наименование категории
      SubsubjectId:
        type: integer
        format: int64
        example: 1
        xml:
          name: SubsubjectId
          attribute: false
          wrapped: false
        description: ИД подкатегории
      SubsubjectName:
        type: string
        example: string
        xml:
          name: SubsubjectName
          attribute: false
          wrapped: false
        description: Наименование подкатегории
      FactId:
        type: integer
        format: int64
        example: 1
        xml:
          name: FactId
          attribute: false
          wrapped: false
        description: ИД факта
      FactName:
        type: string
        example: string
        xml:
          name: FactName
          attribute: false
          wrapped: false
        description: Наименование факта
      AnswerAt:
        type: string
        xml:
          name: AnswerAt
          attribute: false
          wrapped: false
        description: Ответить до
      FastTrack:
        type: boolean
        example: false
        xml:
          name: FastTrack
          attribute: false
          wrapped: false
        description: Признак фасттрека
      CreatedAt:
        type: string
        xml:
          name: CreatedAt
          attribute: false
          wrapped: false
        description: Время создания
      RegionId:
        type: string
        example: string
        xml:
          name: RegionId
          attribute: false
          wrapped: false
        description: ИД региона
      RegionName:
        type: string
        example: string
        xml:
          name: RegionName
          attribute: false
          wrapped: false
        description: Наименование региона
      Address:
        type: string
        example: string
        xml:
          name: Address
          attribute: false
          wrapped: false
        description: Адрес
      OpaId:
        type: integer
        format: int64
        example: 1
        xml:
          name: OpaId
          attribute: false
          wrapped: false
        description: ИД ЛКО
      OpaName:
        type: string
        example: string
        xml:
          name: OpaName
          attribute: false
          wrapped: false
        description: Наименование ЛКО
      Shared:
        type: boolean
        example: false
        xml:
          name: Shared
          attribute: false
          wrapped: false
        description: Признак коллективного сообщения
      Applicant:
        xml:
          name: Applicant
          attribute: false
          wrapped: false
        description: Информация о заявителе
        $ref: '#/definitions/ApplicantType'
      CoApplicants:
        type: array
        xml:
          name: CoApplicants
          namespace: http://pos.gosuslugi.ru/edms/appeal/1.1.0
          attribute: false
          wrapped: true
        description: Информация о со заявителях
        items:
          $ref: '#/definitions/ApplicantType'
      Attachments:
        type: array
        xml:
          name: Attachments
          namespace: http://pos.gosuslugi.ru/edms/appeal/common/1.1.0
          attribute: false
          wrapped: true
        description: Ссылки на прикрепленные файлы
        items:
          type: string
      CustomFieldValues:
        type: array
        xml:
          name: CustomFieldValues
          namespace: http://pos.gosuslugi.ru/edms/appeal/1.1.0
          attribute: false
          wrapped: true
        description: Список настраиваемых полей
        items:
          $ref: '#/definitions/CustomFieldValueType'
      Coordinates:
        type: string
        example: string
        xml:
          name: Coordinates
          attribute: false
          wrapped: false
        description: Координаты адреса проблемы
      LocationAddress:
        xml:
          name: LocationAddress
          attribute: false
          wrapped: false
        description: Информация об адресе проблемы из dadata
        $ref: '#/definitions/AddressType'
    title: EdmsAppealType
    xml:
      name: EdmsAppealType
      attribute: false
      wrapped: false
  ErrorResponse:
    type: object
    required:
      - message
    properties:
      message:
        type: string
        description: Error message
    title: ErrorResponse
    description: ErrorResponse
  FileData:
    type: object
    required:
      - Body
      - MimeType
      - Name
    properties:
      Name:
        type: string
        example: complaint.pdf
        description: Имя файла
      MimeType:
        type: string
        example: application/pdf
        description: Mime-type файла
      Body:
        type: string
        example: >-
          0K3RgtC+INC/0YDQvtGB0YLQviDQv9GA0LjQvNC10YAg0YHRgtGA0L7QutC4INCyIGJhc2U2NC4g0JAg0YfQtdCz0L4g0LLRiyDRgtGD0YIg0LXRidC1INC+0LbQuNC00LDQu9C4INGD0LLQuNC00LXRgtGMPz0p
        description: Файл в base64
    title: FileData
  FileResponse:
    type: object
    required:
      - Body
      - MimeType
      - Name
      - Size
    properties:
      Size:
        type: integer
        format: int64
        example: 465555
        description: Размер
      Name:
        type: string
        example: complaint.pdf
        description: Имя файла
      MimeType:
        type: string
        example: application/pdf
        description: Mime-type файла
      Body:
        type: string
        example: >-
          0K3RgtC+INC/0YDQvtGB0YLQviDQv9GA0LjQvNC10YAg0YHRgtGA0L7QutC4INCyIGJhc2U2NC4g0JAg0YfQtdCz0L4g0LLRiyDRgtGD0YIg0LXRidC1INC+0LbQuNC00LDQu9C4INGD0LLQuNC00LXRgtGMPz0p
        description: Файл в base64
    title: FileResponse
  JsonNode:
    type: object
    title: JsonNode
  ListResponse:
    type: object
    required:
      - Appeals
    properties:
      Appeals:
        type: array
        example:
          - Id: 4654
            Description: Решите, пожалуйста, мою проблему
            RegNumber: null
            RegNumberSetAt: null
            SubjectId: 4
            SubjectName: Благоустройство
            SubsubjectId: 32
            SubsubjectName: Дорожное покрытие
            FactId: 4
            FactName: Отремонтировать дорогу
            AnswerAt: '2021-01-03T23:17:32.100+00:00'
            FastTrack: false
            CreatedAt: '2021-01-03T23:17:32.100+00:00'
            RegionId: 1beeef67-8f2d-4223-9faf-34663033265c
            RegionName: Магаданская область
            Address: Россия, Красноярск, Центральный район, жилой комплекс Светлый
            OpaId: 32
            OpaName: Министерство спорта Магаданской области
            Shared: false
            Applicant:
              Surname: Петров
              Name: Петр
              Patronymic: Петрович
              Email: some@domain.com
              Phone: null
              PostAddress: null
              SendWithRussiaPost: false
            CoApplicants:
              - Surname: Петров
                Name: Петр
                Patronymic: Петрович
                Email: some@domain.com
                Phone: null
                PostAddress: null
                SendWithRussiaPost: false
            Attachments:
              - 1beeef67-8f2d-4223-9faf-34663033265c
              - 1beeef67-8f2d-4223-9faf-34663033265c
            CustomFieldValues:
              - Id: 4
                Name: Размер ямы
                Value: 1x1 метр
                CustomFieldId: 3123
                FieldType: TEXT_FIELD
                DictionaryId: null
                DictionaryValues: null
                Description: null
            Coordinates: 46.30774300,44.26975900
            LocationAddress: null
          - Id: 4654
            Description: Решите, пожалуйста, мою проблему
            RegNumber: null
            RegNumberSetAt: null
            SubjectId: 4
            SubjectName: Благоустройство
            SubsubjectId: 32
            SubsubjectName: Дорожное покрытие
            FactId: 4
            FactName: Отремонтировать дорогу
            AnswerAt: '2021-01-03T23:17:32.100+00:00'
            FastTrack: false
            CreatedAt: '2021-01-03T23:17:32.100+00:00'
            RegionId: 1beeef67-8f2d-4223-9faf-34663033265c
            RegionName: Магаданская область
            Address: Россия, Красноярск, Центральный район, жилой комплекс Светлый
            OpaId: 32
            OpaName: Министерство спорта Магаданской области
            Shared: false
            Applicant:
              Surname: Петров
              Name: Петр
              Patronymic: Петрович
              Email: some@domain.com
              Phone: null
              PostAddress: null
              SendWithRussiaPost: false
            CoApplicants:
              - Surname: Петров
                Name: Петр
                Patronymic: Петрович
                Email: some@domain.com
                Phone: null
                PostAddress: null
                SendWithRussiaPost: false
            Attachments:
              - 1beeef67-8f2d-4223-9faf-34663033265c
              - 1beeef67-8f2d-4223-9faf-34663033265c
            CustomFieldValues:
              - Id: 4
                Name: Размер ямы
                Value: 1x1 метр
                CustomFieldId: 3123
                FieldType: TEXT_FIELD
                DictionaryId: null
                DictionaryValues: null
                Description: null
            Coordinates: 46.30774300,44.26975900
            LocationAddress: null
        description: Массив обращений
        items:
          $ref: '#/definitions/EdmsAppealType'
    title: ListResponse
  PersonEdmsInfoType:
    type: object
    properties:
      Surname:
        type: string
        example: string
        xml:
          name: Surname
          attribute: false
          wrapped: false
        description: Фамилия
      Name:
        type: string
        example: string
        xml:
          name: Name
          attribute: false
          wrapped: false
        description: Имя
      Patronymic:
        type: string
        example: string
        xml:
          name: Patronymic
          attribute: false
          wrapped: false
        description: Отчество
      Email:
        type: string
        example: example@example.org
        xml:
          name: Email
          attribute: false
          wrapped: false
        description: Электронная почта
      Phone:
        type: string
        example: (123) 456-7890
        xml:
          name: Phone
          attribute: false
          wrapped: false
        description: Телефон
    title: PersonEdmsInfoType
    description: Информация о персоне
  Response:
    type: object
    required:
      - Status
    properties:
      Status:
        type: string
        example: OK
        description: HTTP статус сообщения
    title: Response
    description: Сообщение об успешной отправке запроса
  StatusAndFilesRequest:
    type: object
    required:
      - Answer
      - Files
      - Id
      - NotifyApplicant
      - Status
      - StatusText
    properties:
      Id:
        type: integer
        format: int64
        example: 4654
        description: ИД сообщения
      RegNumber:
        type: string
        description: Регистрационный номер
      RegNumberSetAt:
        type: string
        example: 19900101
        description: Дата присвоения регистрационного номера
      OutgoingNumber:
        type: string
        description: Исходящий номер
      OutgoingNumberSetAt:
        type: string
        example: 19900101
        description: Дата присвоения исходящего номера
      OpaId:
        type: integer
        format: int64
        description: ИД ЛКО
      OpaName:
        type: string
        example: string
        description: Наименование ЛКО
      AnswerText:
        type: string
        example: Ваша проблема решена
        xml:
          name: AnswerText
          attribute: false
          wrapped: false
        description: Текст ответа
      Answer:
        type: boolean
        example: true
        description: Признак ответа
      Comment:
        type: string
        xml:
          name: Comment
          attribute: false
          wrapped: false
        description: Комментарий
      Status:
        type: string
        example: TAKEN_TO_WORK
        description: Статус СЭД
      StatusText:
        type: string
        example: Взято в работу
        description: Текст статуса СЭД
      NotifyApplicant:
        type: boolean
        example: false
        description: Признак передачи статуса заявителю
      ReassignmentInfo:
        type: string
        description: Информация о переназначении
      ExecutorInfo:
        example:
          Surname: Петров
          Name: Петр
          Patronymic: Петрович
          Email: some@email.com
          Phone: +7 921 921-92-19
        description: Информация о исполнителе
        $ref: '#/definitions/PersonEdmsInfoType'
      ManagerInfo:
        example:
          Surname: Петров
          Name: Петр
          Patronymic: Петрович
          Email: some@email.com
          Phone: +7 921 921-92-19
        description: Информация о руководителе
        $ref: '#/definitions/PersonEdmsInfoType'
      AppealAnswerType:
        type: string
        example: SOLVED
        description: Тип ответа
        enum:
          - SOLVED
          - POSTPONED
          - NOT_SOLVED
          - FORWARDED
          - REJECTED
      PostponedDate:
        type: string
        example: '2021-01-03T23:20:32.100+00:03'
        description: Дата отложенного сообщения
      AppealIssueType:
        type: string
        example: RESOLVED
        description: Тип проблемы
        enum:
          - NOT_AN_ISSUE
          - INVALID_INPUT
          - TAKEN_INTO_ACCOUNT
          - RESOLVED
      Files:
        type: array
        description: Приложенные файлы в base64
        items:
          $ref: '#/definitions/FileData'
    title: StatusAndFilesRequest
    description: StatusAndFilesRequest
  ValidErrorResponse:
    type: object
    required:
      - message
      - validErrors
    properties:
      message:
        type: string
        description: Error message
      validErrors:
        type: array
        description: valid errors
        items:
          type: string
    title: ValidErrorResponse
    description: ValidErrorResponse
